[[steps]]
name = "Install dependencies"
command = ["fluentci run --wasm bun install"]

[[steps]]
name = "Run playwright tests"
command = [
  "fluentci run --wasm playwright install --with-deps",
  "fluentci run --wasm playwright test -j $(nproc)",
]
env = ["CI=true"]
